# Generated by Django 4.2.6 on 2023-10-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(choices=[('PHY', 'Physics'), ('MAT', 'Maths'), ('BEE', 'BEE'), ('ECO', 'Ecology & Environment'), ('SOC', 'Sociology & Professional Ethics')], default='null', max_length=40)),
                ('types', models.CharField(choices=[('PHY', 'Physics'), ('MAT', 'Maths'), ('BEE', 'BEE'), ('ECO', 'Ecology & Environment'), ('SOC', 'Sociology & Professional Ethics')], default='OTH', max_length=40)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
    ]
