# Generated by Django 4.2.6 on 2023-10-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_material_delete_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='types',
            field=models.CharField(choices=[('SYL', 'Syllabus'), ('NOT', 'Class Notes'), ('BKS', 'Books'), ('PYQ', 'Previous Year Questions'), ('OTH', 'Other')], default='OTH', max_length=40),
        ),
    ]
