# Generated by Django 4.2.6 on 2023-10-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
