# Generated by Django 4.2.6 on 2023-10-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_material_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('desc', models.CharField(default='', max_length=500)),
                ('file', models.FileField(null=True, upload_to='pdf/')),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
    ]
